### ISSUE TITLE
bug : feature 백그라운드 이미지 업로드 문제

### ISSUE THREAD

**Issue by Yenowme** [Chloekkk/Beauty-Saurus#47]
- 링크 백그라운드 이미지 부분 이미지가 새로고침때마다 불러와지기도 하고 아니기도 함

**Comment by leekh716** [comment]
- contenteditable 경고문구 콘솔에서 안뜨게 처리(suppressContentEditableWarning={true})
- 백그라운드 이미지 리렌더링 문제 해결(SettingHoverBtn.tsx 의 let Setting 부분에서 마지막 else에서 Setting = <SettingModal> 로 바꿔줌
- LinkFeatureSetting 에 item 추가시 index + 1 해줬음! 이제 index 같은거 없을듯?!
-
